using System;
using System.Collections.Generic;

namespace biz.erpmet.Model
{
    public partial class CvClientesVistum
    {
        public int IdCliente { get; set; }
        public string Flujo { get; set; }
        public bool? Prospecto { get; set; }
        public string Cliente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public bool? TieneVivienda { get; set; }
        public string Vivienda { get; set; }
        public bool Escriturado { get; set; }
        public bool? ContratoVigente { get; set; }
        public string Contrato { get; set; }
        public bool? TieneCredito { get; set; }
        public string Credito { get; set; }
        public bool? FlujoTerminado { get; set; }
        public string EtapaCliente { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Rfc { get; set; }
        public string NoImss { get; set; }
        public string Telefono { get; set; }
        public string Promocion { get; set; }
        public string Email { get; set; }
        public string Vendedor1 { get; set; }
        public string Vendedor2 { get; set; }
        public string Gerente { get; set; }
        public string Director { get; set; }
        public string VendedorExterno { get; set; }
        public string Vendedor3 { get; set; }
        public string Vendedor4 { get; set; }
        public string FnumeroCredito { get; set; }
        public decimal FmontoAutorizado { get; set; }
        public decimal FmontoPrecalificacion { get; set; }
        public decimal FmontoSalario { get; set; }
        public string Curp { get; set; }
        public string NoSar { get; set; }
        public string NoIssste { get; set; }
        public string NoInfonavit { get; set; }
        public string Calle { get; set; }
        public string NumOficial { get; set; }
        public string NumInterior { get; set; }
        public string Lote { get; set; }
        public string Manzana { get; set; }
        public string Colonia { get; set; }
        public string MpioDeleg { get; set; }
        public string Estado { get; set; }
        public string Localidad { get; set; }
        public string CodPost { get; set; }
        public string FolioIdentificacion { get; set; }
        public string Fnacionalidad { get; set; }
        public string Foriginario { get; set; }
        public string Sexo { get; set; }
        public string FestadoCivil { get; set; }
        public string RegimenMatrimonial { get; set; }
        public string Economia { get; set; }
        public string Casa { get; set; }
        public bool? Aval { get; set; }
        public decimal FingresoMensComp { get; set; }
        public decimal FingresoMensNoComp { get; set; }
        public string FtextoImnc { get; set; }
        public decimal FgastoPromMen { get; set; }
        public decimal FsalarioCuotaDiaria { get; set; }
        public decimal Fsdi { get; set; }
        public short BimestresCotizados { get; set; }
        public string Empresa { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public string Ocupacion { get; set; }
        public string JefeInmediato { get; set; }
        public DateTime? FechaIngreso { get; set; }
        public string TelJefeInmediato { get; set; }
        public decimal MontoEnganche { get; set; }
        public int Area { get; set; }
        public byte Recamaras { get; set; }
        public int Bodega { get; set; }
        public byte Cajones { get; set; }
        public string Medio { get; set; }
        public DateTime? FechaVisita { get; set; }
        public string FcreditoConyugal { get; set; }
        public string Fescolaridad { get; set; }
        public bool? FotrosPatrones { get; set; }
        public byte FpersonasVivenTrab { get; set; }
        public byte Fhmayores18 { get; set; }
        public byte Fhmenores18 { get; set; }
        public bool? Fdiscapacitado { get; set; }
        public string FtipoDiscapacidad { get; set; }
        public bool? FdependienteDiscapacitado { get; set; }
        public string FtipoDiscapacidadDependiente { get; set; }
        public byte FpersonasDiscapacitadas { get; set; }
        public decimal FpensionAlimenticia { get; set; }
        public decimal FsaldoSubcuentaVivienda { get; set; }
        public decimal FmontoAhorro { get; set; }
        public string FaplicarAhorro { get; set; }
        public decimal Fcalificacion { get; set; }
        public string FdelegacionInfonavit { get; set; }
        public decimal FpuntosInfonavit { get; set; }
        public int IdProyecto { get; set; }
        public string TelefonoCelular { get; set; }
        public decimal IngresoAnual { get; set; }
        public string PrototipoDeseado { get; set; }
        public string NoAfore { get; set; }
        public decimal IngresoPresupuestal { get; set; }
        public string NoFovissste { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public bool TelefonosConfirmados { get; set; }
        public string Identificacion { get; set; }
        public string NombreConyuge { get; set; }
        public int? IdCredito { get; set; }
        public string SofolCredito { get; set; }
        public string Referencia { get; set; }
        public decimal MontoFichaRapApartado { get; set; }
        public DateTime? FechaFichaRapApartado { get; set; }
        public string SofolSolicitada { get; set; }
        public bool EscrituradoReal { get; set; }
        public int? Folioapartado { get; set; }
        public int? Folioporproyecto { get; set; }
        public string Pais { get; set; }
        public string CuentaBancaria { get; set; }
        public string BancoSat { get; set; }
        public string FformaCredito { get; set; }
        public string FplazoCredito { get; set; }
        public bool FesOfertaVinculante { get; set; }
        public bool PagoElectronico { get; set; }
        public string MonedaSatdefault { get; set; }
    }
}
