using System;
using System.Collections.Generic;

namespace biz.erpmet.Model
{
    public partial class CvViviendasVistum
    {
        public int IdVivienda { get; set; }
        public string Flujo { get; set; }
        public string Vivienda { get; set; }
        public string Texto { get; set; }
        public string Plaza { get; set; }
        public string Desarrollo { get; set; }
        public bool? TieneCliente { get; set; }
        public string EtapaConstruccion { get; set; }
        public string Prototipo { get; set; }
        public int? IdCliente { get; set; }
        public string Cliente { get; set; }
        public string Centro { get; set; }
        public int? IdEtapaVivienda { get; set; }
        public int? IdEtapaCliente { get; set; }
        public int IdPrototipo { get; set; }
        public string ObjetoAutocad { get; set; }
        public string Vinculada { get; set; }
        public string EtapaVivienda { get; set; }
        public string EtapaCliente { get; set; }
        public string LicConstruccion { get; set; }
        public string ClaveCatastral { get; set; }
        public string BoletaPredial { get; set; }
        public DateTime? FechaHabitabilidad { get; set; }
        public string TipoVivienda { get; set; }
        public string TipoLote { get; set; }
        public string Vlote { get; set; }
        public decimal PrecioReal { get; set; }
        public decimal Enganche { get; set; }
        public decimal PrecioTerreno { get; set; }
        public DateTime? FechaAvaluo { get; set; }
        public decimal ValorAvaluo { get; set; }
        public int? MonedaCos { get; set; }
        public byte FnoDormitorios { get; set; }
        public string Festado { get; set; }
        public string Fsector { get; set; }
        public byte FnoCuartos { get; set; }
        public bool FdictamenAprobado { get; set; }
        public string FtipoMercado { get; set; }
        public string FlineaDeCredito { get; set; }
        public string FtipoOfertacion { get; set; }
        public string FtipoCompra { get; set; }
        public string NotariaInd { get; set; }
        public bool? Individualizada { get; set; }
        public string LugarIndividual { get; set; }
        public DateTime? FechaIndividual { get; set; }
        public string EscrituraIndividual { get; set; }
        public string EscrituraLote { get; set; }
        public string NotariaLot { get; set; }
        public decimal LiberacionPesos { get; set; }
        public decimal PrecioPuente { get; set; }
        public decimal LiberacionPuente { get; set; }
        public DateTime? FechaLiberacion { get; set; }
        public int? MonedaPuente { get; set; }
        public string NoCreditoPuente { get; set; }
        public string SofolPuente { get; set; }
        public DateTime? FechaFirmaPuente { get; set; }
        public string NoEscrituraPuente { get; set; }
        public string NotariaPuente { get; set; }
        public bool IncluirEnCreditoPuente { get; set; }
        public decimal MontoComisionPuente { get; set; }
        public decimal MontoAmortizacionPuente { get; set; }
        public string M2indiviso { get; set; }
        public string M2excedente { get; set; }
        public string M2construccion { get; set; }
        public string M2terreno { get; set; }
        public string NumInterior { get; set; }
        public string NumOficial { get; set; }
        public string Calle { get; set; }
        public string Fraccionamiento { get; set; }
        public string CodPost { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Colonia { get; set; }
        public int IdProyecto { get; set; }
        public string Promocion { get; set; }
        public bool PromocionEntregada { get; set; }
        public DateTime? FechaEntregaPromocion { get; set; }
        public string Manzana { get; set; }
        public string Observaciones { get; set; }
        public string Seccion { get; set; }
        public string Sucursal { get; set; }
        public DateTime? FechaModificacionFlujo { get; set; }
        public decimal? PorcentajeAvance { get; set; }
        public string FolioRegistroPublicoProp { get; set; }
        public string LicenciaUsoDeSuelo { get; set; }
        public decimal PavanceInfonavit { get; set; }
        public decimal PavanceSupervision { get; set; }
        public int? ColorRellenoViv { get; set; }
        public int? TipoRellenoViv { get; set; }
        public string AnsiViv { get; set; }
        public decimal EscalaRellenoViv { get; set; }
        public int? ColorRellenoCli { get; set; }
        public int? TipoRellenoCli { get; set; }
        public string AnsiCli { get; set; }
        public decimal? EscalaRellenoCli { get; set; }
        public string Credito { get; set; }
        public DateTime? FechaEntregaCliente { get; set; }
        public string SubtipoTerreno { get; set; }
        public decimal CostoTerreno { get; set; }
        public decimal CostoVivienda { get; set; }
    }
}
