using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class Contact
    {
        public Contact()
        {
            ChangeOrderRevisions = new HashSet<ChangeOrderRevision>();
            ContractContacts = new HashSet<ContractContact>();
            DocumentDistributionListRecipients = new HashSet<DocumentDistributionListRecipient>();
            DocumentPackageRecipients = new HashSet<DocumentPackageRecipient>();
            DocumentRevisions = new HashSet<DocumentRevision>();
            DocumentTransmittalRecipients = new HashSet<DocumentTransmittalRecipient>();
            DocumentTransmittalRevisions = new HashSet<DocumentTransmittalRevision>();
            EnquiryProjectPeople = new HashSet<EnquiryProjectPerson>();
        }

        /// <summary>
        /// Unique Contact ID automatically generated by system.
        /// </summary>
        public int ContactId { get; set; }
        /// <summary>
        /// Full Name of Contact
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Contact Title (eg. Mr/Mrs Sir/Dr)
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// Contact First Name
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// Contact Surname
        /// </summary>
        public string Surname { get; set; }
        /// <summary>
        /// Contact Job Title
        /// </summary>
        public string JobTitle { get; set; }
        /// <summary>
        /// Company Phone Number
        /// </summary>
        public string CompanyNumber { get; set; }
        /// <summary>
        /// Home Phone Number
        /// </summary>
        public string HomeNumber { get; set; }
        /// <summary>
        /// Mobile Phone Number
        /// </summary>
        public string MobileNumber { get; set; }
        /// <summary>
        /// Fax Number
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// Primary Email Contact Address
        /// </summary>
        public string Email1 { get; set; }
        /// <summary>
        /// Alternative Email Contact Address
        /// </summary>
        public string Email2 { get; set; }
        /// <summary>
        /// Notes
        /// </summary>
        public string Notes { get; set; }
        /// <summary>
        /// The date of the last update.
        /// </summary>
        public DateTime? UpdatedOn { get; set; }
        /// <summary>
        /// The last updater
        /// </summary>
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Date the record was created.
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// The record creator
        /// </summary>
        public string CreatedBy { get; set; }
        public int Version { get; set; }
        public byte? System { get; set; }
        /// <summary>
        /// Is this a Document Management Contact?
        /// </summary>
        public bool? IsDocumentManagementContact { get; set; }
        /// <summary>
        /// Default Number of Days it takes for this Contact to Respond
        /// </summary>
        public int? DefaultResponseDays { get; set; }
        /// <summary>
        /// Will this Contact Require Acknowledgement on Transmittals?
        /// </summary>
        public bool? DefaultAcknowledgement { get; set; }
        /// <summary>
        /// Default Reason why this Contact is given Documents
        /// </summary>
        public int? DocumentTransmittalReasonId { get; set; }
        /// <summary>
        /// Default Number of copies that this Contact receives
        /// </summary>
        public int? Copies { get; set; }
        /// <summary>
        /// ~Default Email Priority (1=Highest, 2=High, 3=Normal, 4=Low, 5=Lowest)
        /// </summary>
        public int? PriorityId { get; set; }
        public double? MaxEmailSize { get; set; }
        /// <summary>
        /// The Default Signature used by this contact on Emails (Optional)
        /// </summary>
        public string Signature { get; set; }
        /// <summary>
        /// Optional Field for storing default zip password for Locking Transmittal Zip Files
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// Login Name for Contact
        /// </summary>
        public string Login { get; set; }
        public bool PrimaryContact { get; set; }
        public int? AddressId { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<ChangeOrderRevision> ChangeOrderRevisions { get; set; }
        public virtual ICollection<ContractContact> ContractContacts { get; set; }
        public virtual ICollection<DocumentDistributionListRecipient> DocumentDistributionListRecipients { get; set; }
        public virtual ICollection<DocumentPackageRecipient> DocumentPackageRecipients { get; set; }
        public virtual ICollection<DocumentRevision> DocumentRevisions { get; set; }
        public virtual ICollection<DocumentTransmittalRecipient> DocumentTransmittalRecipients { get; set; }
        public virtual ICollection<DocumentTransmittalRevision> DocumentTransmittalRevisions { get; set; }
        public virtual ICollection<EnquiryProjectPerson> EnquiryProjectPeople { get; set; }
    }
}
