using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class ContractDetailedCadlisting
    {
        public int ContractDetailedCadlistingId { get; set; }
        public int ContractListingId { get; set; }
        public int CadinterfaceId { get; set; }
        public string SourceItemCrossReference { get; set; }
        public string PlateItemCrossReference { get; set; }
        public int? ItemId { get; set; }
        public string Name { get; set; }
        public string SourceSectionSize { get; set; }
        public string SourceGrade { get; set; }
        public string SourceAmark { get; set; }
        public string SourceMark { get; set; }
        public string SourceItemMark { get; set; }
        public string SourcePrelimMark { get; set; }
        public double? SourceQuantity { get; set; }
        public double? SourceLength { get; set; }
        public double? SourceWidth { get; set; }
        public double? SourceThickness { get; set; }
        public double? SourceDepth { get; set; }
        public string SourcePhase { get; set; }
        public string SourceLot { get; set; }
        public string SourcePaintFinish { get; set; }
        public string SourceDetails { get; set; }
        public string SourceSiteMemberId { get; set; }
        public string SourceSiteMember { get; set; }
        public string SourceMainMember { get; set; }
        public string SourceIsShaft { get; set; }
        public string SourceReference { get; set; }
        public string SourceCutType { get; set; }
        public byte Ignore { get; set; }
        public byte InvalidMark { get; set; }
        public double? TempLength { get; set; }
        public int TempKey { get; set; }
        public int RevisionStatus { get; set; }
        public long RevisionIndex { get; set; }
        public string RevisionDetails { get; set; }
        public int StatusIndex { get; set; }
        public string MarkItemStatus { get; set; }
        public int MinimumRevisibleStatus { get; set; }
        public byte AllowRevision { get; set; }
        public int ParentMarkId { get; set; }
        public bool HasItemOnLoad { get; set; }
        public string SourceRevision { get; set; }
        public string SourceStartWebAngle { get; set; }
        public string SourceEndWebAngle { get; set; }
        public string SourceWeight { get; set; }
        public string SourceArea { get; set; }
        public string SourceAssemblyId { get; set; }
        public string SourceStartTopFlangeAngle { get; set; }
        public string SourceEndTopFlangeAngle { get; set; }
        public string SourceStartBottomFlangeAngle { get; set; }
        public string SourceEndBottomFlangeAngle { get; set; }
        public string CustomFields { get; set; }
        public string SessionGuid { get; set; }
        public int? RemoveMarkItemId { get; set; }
        public string SourceAssemblyMarkGuid { get; set; }
        public string SourceMarkGuid { get; set; }
        public string SourceMarkItemGuid { get; set; }
        public string SourceModelType { get; set; }
        public bool CamSplitItem { get; set; }
        public int? ReceiveIntoInventoryId { get; set; }
        public string SourceGirderBfthickness { get; set; }
        public string SourceGirderBfwidth { get; set; }
        public string SourceGirderDepth { get; set; }
        public string SourceGirderShape { get; set; }
        public string SourceGirderTfthickness { get; set; }
        public string SourceGirderTfwidth { get; set; }
        public string SourceGirderType { get; set; }
        public string SourceGirderWebOffset { get; set; }
        public string SourceGirderWebThickness { get; set; }
        public string SourceSectionType { get; set; }
        public string SourceExecutionClass { get; set; }
        public string SourceBottomFlangeGrade { get; set; }
        public string SourceBottomFlangeThickness { get; set; }
        public string SourceBottomFlangeWeld { get; set; }
        public string SourceBottomFlangeWidth { get; set; }
        public string SourceCambering { get; set; }
        public string SourceGrossLength { get; set; }
        public string SourceRadius { get; set; }
        public string SourceTopFlangeGrade { get; set; }
        public string SourceTopFlangeThickness { get; set; }
        public string SourceTopFlangeWeld { get; set; }
        public string SourceTopFlangeWidth { get; set; }
        public string SourceWebGrade { get; set; }
        public string SourceWebHeight { get; set; }
        public string SourceWebThickness { get; set; }
        public bool ForceOnHoldItem { get; set; }
        public int? ContractMarkInstanceId { get; set; }
        public string InvalidMarkReason { get; set; }
        public string IsOfTypeCodeFlat { get; set; }
        public string IsOfTypeCodePlate { get; set; }
        public int? ChksourceSectionSize { get; set; }
        public int? CmiSwap { get; set; }
        public int? CmiiSwap { get; set; }
        public string NameChange { get; set; }
        public DateTime? Importdate { get; set; }
        public int? ChksessionGuid { get; set; }
        public int? TmpCmiId { get; set; }
        public int? TmpCmiiId { get; set; }
        public bool? RevisionHold { get; set; }
    }
}
