using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class ContractBatchContract
    {
        /// <summary>
        /// Unique Contract Batch Contract ID automatically generated by system.
        /// </summary>
        public int ContractBatchContractId { get; set; }
        /// <summary>
        /// Contract Batch ID this entry is linked to.
        /// </summary>
        public int ContractBatchId { get; set; }
        /// <summary>
        /// Contract ID this entry refers to.
        /// </summary>
        public int ContractId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ContractBatch ContractBatch { get; set; }
    }
}
