using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class EdifileContract
    {
        /// <summary>
        /// Unique EDI File Contract ID automatically generated by system.
        /// </summary>
        public int EdifileContractId { get; set; }
        /// <summary>
        /// EDI File ID this entry is linked to.
        /// </summary>
        public int EdifileId { get; set; }
        /// <summary>
        /// Contract ID this entry refers to.
        /// </summary>
        public int? ContractId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Edifile Edifile { get; set; }
    }
}
