using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class PurchaseInvoiceItemContract
    {
        /// <summary>
        /// Unique Purchase Invoice Contract ID automatically generated by system.
        /// </summary>
        public int PurchaseInvoiceItemContractId { get; set; }
        /// <summary>
        /// Purchase Invoice Item ID this entry is linked to.
        /// </summary>
        public int PurchaseInvoiceItemId { get; set; }
        /// <summary>
        /// Contract ID this entry refers to.
        /// </summary>
        public int? ContractId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual PurchaseInvoiceItem PurchaseInvoiceItem { get; set; }
    }
}
