using System;
using System.Collections.Generic;

namespace biz.metalitec.Models
{
    public partial class SystemObjectUserField
    {
        public int SystemObjectUserFieldId { get; set; }
        public int SystemObjectId { get; set; }
        public bool String1Active { get; set; }
        public string String1Label { get; set; }
        public bool String2Active { get; set; }
        public string String2Label { get; set; }
        public bool String3Active { get; set; }
        public string String3Label { get; set; }
        public bool String4Active { get; set; }
        public string String4Label { get; set; }
        public bool String5Active { get; set; }
        public string String5Label { get; set; }
        public bool String6Active { get; set; }
        public string String6Label { get; set; }
        public bool String7Active { get; set; }
        public string String7Label { get; set; }
        public bool String8Active { get; set; }
        public string String8Label { get; set; }
        public bool Float1Active { get; set; }
        public string Float1Label { get; set; }
        public bool Float2Active { get; set; }
        public string Float2Label { get; set; }
        public bool Float3Active { get; set; }
        public string Float3Label { get; set; }
        public bool Float4Active { get; set; }
        public string Float4Label { get; set; }
        public bool Bool1Active { get; set; }
        public string Bool1Label { get; set; }
        public bool Bool2Active { get; set; }
        public string Bool2Label { get; set; }
        public bool Bool3Active { get; set; }
        public string Bool3Label { get; set; }
        public bool Bool4Active { get; set; }
        public string Bool4Label { get; set; }
        public bool DateTime1Active { get; set; }
        public string DateTime1Label { get; set; }
        public bool DateTime2Active { get; set; }
        public string DateTime2Label { get; set; }
        public bool DateTime3Active { get; set; }
        public string DateTime3Label { get; set; }
        public bool DateTime4Active { get; set; }
        public string DateTime4Label { get; set; }
        public bool String9Active { get; set; }
        public string String9Label { get; set; }
        public bool String10Active { get; set; }
        public string String10Label { get; set; }
        public bool String11Active { get; set; }
        public string String11Label { get; set; }
        public bool String12Active { get; set; }
        public string String12Label { get; set; }
        public bool String13Active { get; set; }
        public string String13Label { get; set; }
        public bool String14Active { get; set; }
        public string String14Label { get; set; }
        public bool String15Active { get; set; }
        public string String15Label { get; set; }
        public bool String16Active { get; set; }
        public string String16Label { get; set; }
        public bool String17Active { get; set; }
        public string String17Label { get; set; }
        public bool String18Active { get; set; }
        public string String18Label { get; set; }
        public bool String19Active { get; set; }
        public string String19Label { get; set; }
        public bool String20Active { get; set; }
        public string String20Label { get; set; }
        public bool String21Active { get; set; }
        public string String21Label { get; set; }
        public bool String22Active { get; set; }
        public string String22Label { get; set; }
        public bool Float5Active { get; set; }
        public string Float5Label { get; set; }
        public bool Float6Active { get; set; }
        public string Float6Label { get; set; }
        public bool Float7Active { get; set; }
        public string Float7Label { get; set; }
        public bool Float8Active { get; set; }
        public string Float8Label { get; set; }
        public bool DateTime5Active { get; set; }
        public string DateTime5Label { get; set; }
        public bool DateTime6Active { get; set; }
        public string DateTime6Label { get; set; }
        public int? Version { get; set; }
        public bool? String1Mandatory { get; set; }
        public bool? String2Mandatory { get; set; }
        public bool? String3Mandatory { get; set; }
        public bool? String4Mandatory { get; set; }
        public bool? String5Mandatory { get; set; }
        public bool? String6Mandatory { get; set; }
        public bool? String7Mandatory { get; set; }
        public bool? String8Mandatory { get; set; }
        public bool? String9Mandatory { get; set; }
        public bool? String10Mandatory { get; set; }
        public bool? String11Mandatory { get; set; }
        public bool? String12Mandatory { get; set; }
        public bool? String13Mandatory { get; set; }
        public bool? String14Mandatory { get; set; }
        public bool? String15Mandatory { get; set; }
        public bool? String16Mandatory { get; set; }
        public bool? String17Mandatory { get; set; }
        public bool? String18Mandatory { get; set; }
        public bool? String19Mandatory { get; set; }
        public bool? String20Mandatory { get; set; }
        public bool? String21Mandatory { get; set; }
        public bool? String22Mandatory { get; set; }
        public bool? Float1Mandatory { get; set; }
        public bool? Float2Mandatory { get; set; }
        public bool? Float3Mandatory { get; set; }
        public bool? Float4Mandatory { get; set; }
        public bool? Float5Mandatory { get; set; }
        public bool? Float6Mandatory { get; set; }
        public bool? Float7Mandatory { get; set; }
        public bool? Float8Mandatory { get; set; }
        public bool? Bool1Mandatory { get; set; }
        public bool? Bool2Mandatory { get; set; }
        public bool? Bool3Mandatory { get; set; }
        public bool? Bool4Mandatory { get; set; }
        public bool? DateTime1Mandatory { get; set; }
        public bool? DateTime2Mandatory { get; set; }
        public bool? DateTime3Mandatory { get; set; }
        public bool? DateTime4Mandatory { get; set; }
        public bool? DateTime5Mandatory { get; set; }
        public bool? DateTime6Mandatory { get; set; }
    }
}
